options:
  dateformat:
    weekday: short
    year: numeric
    month: long
    day: numeric
    hour: numeric
    minute: 2-digit
variables:
  socketio:
    APP:
      LOADED: app_loaded
    CHANNELS:
      UPDATE:
        ANNOUNCE: channels_announce_update
        REQUEST: channels_request_update
        HTML: channels_html
      JOIN: channel_join
      CREATE:
        NEW: channel_create
        SUCCESS: channel_create_success
        ERROR: channel_create_error   
    USERS:
      UPDATE:
        ANNOUNCE: users_announce_update
        REQUEST: users_request_update
        HTML: users_html
    CURRENT_CHAT:
      UPDATED: current_chat_updated
    CHAT:
      HTML: chat_html
      LOAD: chat_load
    PROFILE:
      HTML: profile_html
      LOAD: profile_load
    MESSAGE:
      SEND: message_send
      RECEIVED: message_received
    USERDATA:
      UPDATE: userdata_update
      STATUS: 
        UPDATED: status_updated
  template:
    USERS:
      SELF:
        NAME: "username"
        CURRENT_CHAT: current_chat
        CURRENT_CHAT_DATA: current_chat_data
      ALL:
        DATA: "all_users_data"
      ONE:
        DATA: "user_data"
        CHANNELS: "user_channels"
    CHANNELS:
      ALL: "all_channels"
      SELF: "self_channels"
      ONE:
        MEMBERS: "members"
    MESSAGES:
      CHANNEL: "channel_messages"
assets:
  BLANK_PIXEL: "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"
  SVG:
    CHANNEL: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100%25' height='100%25' style='background: %23212734' viewBox='-3 -3 28 20'%3E%3Cpath fill='%23a6a9ae' d='M22 11.5V14h-6v-2.5c0-1.48-.81-2.61-1.97-3.45.35-.03.68-.05.97-.05 2.33 0 7 1.17 7 3.5zm-8 0V14H0v-2.5C0 9.17 4.67 8 7 8s7 1.17 7 3.5zM4 3c0-1.66 1.34-3 3-3s2.99 1.34 2.99 3S8.66 6 7 6C5.34 6 4 4.66 4 3zm8 0c0-1.66 1.34-3 3-3s2.99 1.34 2.99 3S16.66 6 15 6c-1.66 0-3-1.34-3-3z'/%3E%3C/svg%3E"
content:
  modal:
    prompt:
      channel:
        title: "Create channel"
        input-group: 
            - label: "Enter new channel name:"
              name: "channel_name"
              type: "text"
data:
  users:
    Admin:
      avatar: avatar_Admin_1585346729664.png
      location: "New York New York"
      status: "online"
      sid: 0
    Miu:
      avatar: "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"
      location: Athens
      status: busy
      sid: 0
  user_in_channels:
    Admin:
      - General
      - Offtopic
    Miu:
      - General
  channel_members:
    General:
      - Admin
      - Miu
    Offtopic:
      - Admin
  default_channels:
    - General
    - Offtopic
  messages:
    General:
      - sender: Admin
        timestamp: "2020-02-26T12:04:10+02:00"
        message: It’s hard to say when in our lives each of us become
      - sender: Miu
        timestamp: "2020-02-28T12:04:10+02:00"
        message: It’s lorem ipsum!
    Offtopic:
  sid:
    Admin:
      - 12345
      - 23456
    Miu:
